[package]
name = "reverse_polish"
version = "0.1.0"
authors = ["strix <p.smagin@napoleonit.ru>"]
edition = "2018"

[workspace]
members = ["reverse"] 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reverse = { path = "reverse" }